source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'JVCategories_Example' do
    pod 'JVCategories', :path => '../'
end

target 'JVCategories_Tests' do
    pod 'JVCategories', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        puts "#{target.name}"
    end
end
