source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JVCategories_Example', :exclusive => true do
  pod "JVCategories", :path => "../"
end

target 'JVCategories_Tests', :exclusive => true do
  pod "JVCategories", :path => "../"

  
end
